<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="1" name="" skips="0" tests="1" time="7.110"><testcase classname="scripts.LoginTest.CheckLoginExample" name="test_login_show_gear" time="4.76973319054"><failure message="test failure">Traceback (most recent call last):
  File &quot;/Users/apailthorp/pysaunter_spike/conftest.py&quot;, line 32, in pytest_runtest_call
    raise(e)
AssertionError: assert &lt;bound method LoginPage.login of &lt;pages.login.LoginPage object at 0x10ac48390&gt;&gt;(&apos;g_user&apos;, &apos;testtest&apos;)
 +  where &lt;bound method LoginPage.login of &lt;pages.login.LoginPage object at 0x10ac48390&gt;&gt; = &lt;pages.login.LoginPage object at 0x10ac48390&gt;.login</failure></testcase></testsuite>